chore: add source to transcript card
bitcointranscripts/registry pull request #60
Opened 2024-11-19 07:12 UTC by IgboPharaoh

fixes #58

2024-11-28 14:34 UTC, Emmanuel-Develops requested changes

2024-11-28 14:34 UTC, Emmanuel-Develops commented on src/components/landing-page/TranscriptCard.tsx
> +  const mappedKeyToName = SourceCountData.find((source) => source.slug === data.slugAsParams[0])?.name;
can we move this to the page component and pass the data as props

2024-11-28 20:12 UTC, Emmanuel-Develops commented on src/components/landing-page/featured-transcripts/FeaturedTranscriptClient.tsx
> +  const getSourceFromTranscript = (data: Transcript) =>
I meant, we get this data on the server component before it gets to this client component.

We should always offload logic to server components when we can.
For best performance we would have to modify the functions that get "featured" and "latest" transcripts.

home page load doesn't indicate any extra processing, further optimizations should in a separate PR for complete evaluation

2024-11-28 20:18 UTC, merged

2024-12-04 15:06 UTC, kouloumos reviewed
@IgboPharaoh , @Emmanuel-Develops , the cards in the "Dive into Transcripts" section are not clickable anymore and I think that this is the PR that introduced the issue into production.
Clicking on the cards doesn't work in the preview of this PR.
Needs further investigation.

2024-12-04 16:01 UTC, IgboPharaoh commented
Great catch andreas, the issue is definitely from this pr and the mistake is from my end. I'll fix it shortly. 

Thanks

2024-12-04 22:36 UTC, IgboPharaoh commented
> @IgboPharaoh , @Emmanuel-Develops , the cards in the "Dive into Transcripts" section are not clickable anymore and I think that this is the PR that introduced the issue into production. Clicking on the cards doesn't work in the preview of this PR. Needs further investigation.

#68 fixes this issue