Feat/About page
bitcointranscripts/registry pull request #69
Opened 2024-12-07 09:08 UTC by IgboPharaoh

This pr adds the About page :
- Adds design, icons and media responsiveness
- Add setup script to fetch reviewer data from [bitcointranscripts](https://api.github.com/repos/bitcointranscripts/bitcointranscripts) repository

A GITHUB_ACCESS_TOKEN will be needed to test this implementation
A further discussion is needed on this to finalise this implementation

2024-12-07 18:04 UTC, Emmanuel-Develops commented
> The deployment is failing as a GITHUB_ACCESS_TOKEN will be needed to test this implementation. 
Added acces token and deployed

2024-12-10 16:08 UTC, Emmanuel-Develops requested changes
Looks good!

only a couple of changes

2024-12-10 16:08 UTC, Emmanuel-Develops commented on scripts/fetchReviewers.js
> +if (!process.env.GITHUB_ACCESS_TOKEN) {
also add a check for prod.
i.e (!process.env. GITHUB_ACCESS_TOKEN && process.env.NODE_ENV === "production")

having dev contributors generate gh keys to run adds extra restrictions

2024-12-11 08:15 UTC, IgboPharaoh commented on scripts/fetchReviewers.js
> +  const trimText = (text) => (text.length > 15 ? text.substring(0, 15) + "..." : text);
There is no loss of information here as we are only trimming the string so reviewer title fits into the grid box

2024-12-11 10:28 UTC, IgboPharaoh commented on scripts/fetchReviewers.js
> +    reviewers[login] = { image: avatar_url, title: trimText(login) };
Its a matter of choice. I am using the the key to add reviewer data to the object which makes the addition on one pass. Using an array I will have to define a condition before it is been added and but for an object, new items with the same key replace existing items with the same key inside the object ensuring every item is unique without setting an extra condition.

2024-12-17 08:12 UTC, kouloumos commented on src/app/about/page.tsx
> +            subText='Editors evaluate and finalize Reviewers submissions, ensuring they’re consistently high quality.'
wrong copy here

2024-12-17 09:03 UTC, Emmanuel-Develops commented
Nice work!
The link is linked to a trimmed version of the user github profile (for long usernames).
e.g `https://github.com/Emmanuel-Develo...`, `https://github.com/ai-transcriber[...`, `https://github.com/alexanderwieder...`

which correlates with [this comment](https://github.com/bitcointranscripts/registry/pull/69#discussion_r1878307775)

it helps to have visual changes in the FE while we keep information intact. We can limit the characters with CSS in the component itself. This will be more dynamic and there won't be information loss
cc: @IgboPharaoh

2024-12-17 09:58 UTC, Emmanuel-Develops commented
> Great point which I didn't factor in, I've made necessary changes to fix this.

nice. You can also limit with CSS using
```css
    max-width: 100%;
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
```
on the `p` tag.
from the preview deployment, it looks fine without the trim, solely because we do not have very long usernames.
I'm not peculiar on either but to account for future changes, the CSS trim is a good way to go
cc: @IgboPharaoh

2024-12-18 07:50 UTC, Emmanuel-Develops approved these changes

2024-12-18 07:51 UTC, Emmanuel-Develops commented
ACK!

@IgboPharaoh this looks good. Merging!

you can complete the dashed linking in a new PR

2024-12-18 07:52 UTC, merged