Nested headings for Transcript Page
bitcointranscripts/registry pull request #75
Opened 2024-12-28 19:04 UTC by 0tuedon

This PR adds support for nested transcript navigation chapters and closes issue #64 .

2025-01-08 12:06 UTC, Emmanuel-Develops requested changes

2025-01-08 12:06 UTC, Emmanuel-Develops commented on src/components/explore/TranscriptContentPage.tsx
> +      ? (groupDataByAlphabet(data) as Omit<GroupedData, "nested">)
I and @0tuedon had an extensive call to refactor the grouping component. It should take a specific data type and render it. Removing the need to check if `isTranscript` or omitting `nested` field

For simplicity the data transformation logic exists outside the component and returns an array of 
``` ts
{ name: string, slug: string, count?: number, nested?: boolean }
```

2025-01-09 04:24 UTC, IgboPharaoh commented
Hello @0tuedon can you please rebase your branch to the latest on staging

2025-01-09 15:44 UTC, 0tuedon commented
This new commit [cb3712c](https://github.com/bitcointranscripts/registry/pull/75/commits/cb3712cf512d1a55c5fb0d67174d347c3c2bc0c7) is meant to changed the complex data structure  we had for Content Page and Content Grouping. This should resolve comments made by @kouloumos  and @Emmanuel-Develops.

There might still be some nit fixes and I will need extra eyes on this.
cc @IgboPharaoh  @Emmanuel-Develops @kouloumos

2025-01-09 23:08 UTC, Emmanuel-Develops requested changes

2025-01-13 00:06 UTC, 0tuedon commented on src/components/explore/AlphabetGrouping.tsx
> +        char?.nested&& char?.nested.length > 0 ? (
Used to check if disabled

2025-01-14 08:25 UTC, IgboPharaoh commented on src/components/explore/TranscriptContentPage.tsx
> +  // [{name: "A", slug:"a", nested: [{name: "ABC", count: 1}]}]
We can remove commented out code here

2025-01-14 08:43 UTC, IgboPharaoh commented on src/components/explore/TranscriptContentPage.tsx
> +  // [{name: "A", slug:"a", nested: [{name: "ABC", count: 1}]}]
Ohhhh, please can you add a comment explaining that ?

2025-01-14 08:53 UTC, IgboPharaoh commented
While reviewing the PR, I tested the links in the example transcript tagged in the PR description and I noticed that clicking on them don't navigate you to a new page while retaining the bitcoin transcripts in its own tab but you're routed to the page inside the existing transcript page hence taking you out of the app.

Is this the expected behaviour we want when we click on external links when reading a transcript ? @0tuedon @Emmanuel-Develops @kouloumos

2025-01-14 09:14 UTC, 0tuedon commented
> While reviewing the PR, I tested the links in the example transcript tagged in the PR description and I noticed that clicking on them don't navigate you to a new page while retaining the bitcoin transcripts in its own tab but you're routed to the page inside the existing transcript page hence taking you out of the app.
> 
> Is this the expected behaviour we want when we click on external links when reading a transcript ? @0tuedon @Emmanuel-Develops @kouloumos

Oh yh I agree this can be done, not sure if I asked the question before (looks familiar) waiting for confirmation from @kouloumos  and @Emmanuel-Develops .

2025-01-14 12:57 UTC, Emmanuel-Develops requested changes
Looks good, left some few nits

2025-01-14 12:57 UTC, Emmanuel-Develops commented on src/components/explore/GroupedTranscriptContent.tsx
>    return type === "alphabet" ? (
the two components from conditional rendering are more or less the same

2025-01-14 12:57 UTC, Emmanuel-Develops commented on src/components/explore/ContentGrouping.tsx
>  const ContentGrouping = ({
This naming doesn't seem very descriptive.
Its more or less Navigation by words right?
There are a lot of components with grouping and transcript names in them it can be hard to track

2025-01-14 12:57 UTC, Emmanuel-Develops commented on src/components/explore/AlphabetGrouping.tsx
>  const AlphabetGrouping = ({ currentGroup, groupedData }: IAlphabetGrouping) => {
Same here, `AlphabetNavigation` is fine, same as `MobileAlphabetNavigation`

2025-01-14 13:04 UTC, 0tuedon commented on src/components/explore/ContentGrouping.tsx
>  const ContentGrouping = ({
Yh, it is

2025-01-14 13:04 UTC, 0tuedon commented on src/components/explore/AlphabetGrouping.tsx
>  const AlphabetGrouping = ({ currentGroup, groupedData }: IAlphabetGrouping) => {
Okay

2025-01-14 15:16 UTC, 0tuedon commented on src/components/explore/TranscriptContentPage.tsx
>            {groupedData &&
Yh just before but that has been fixed from our refactor.

2025-01-16 18:58 UTC, merged